// <auto-generated />
using System;
using BridgertonGame.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BridgertonGame.Server.Migrations
{
    [DbContext(typeof(BridgertonDbContext))]
    [Migration("20260318153926_AddQuizSystem")]
    partial class AddQuizSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BridgertonGame.Server.Data.Entities.AdminCredential", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("AdminCredentials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "$2a$11$.xWcpRppD8w3HclskFBxK.lsb3oPqKPXziJn/3yEpSG0pW65v.n2K",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("BridgertonGame.Server.Data.Entities.GameScoreEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FamilyId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GameScores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FamilyId = "hastings",
                            GameName = "Total",
                            Score = 230
                        },
                        new
                        {
                            Id = 2,
                            FamilyId = "bridgerton",
                            GameName = "Total",
                            Score = 230
                        },
                        new
                        {
                            Id = 3,
                            FamilyId = "featherington",
                            GameName = "Total",
                            Score = 230
                        },
                        new
                        {
                            Id = 4,
                            FamilyId = "danbury",
                            GameName = "Total",
                            Score = 230
                        },
                        new
                        {
                            Id = 5,
                            FamilyId = "sharma",
                            GameName = "Total",
                            Score = 230
                        },
                        new
                        {
                            Id = 6,
                            FamilyId = "hastings",
                            GameName = "Jeu 1",
                            Score = 230
                        },
                        new
                        {
                            Id = 7,
                            FamilyId = "bridgerton",
                            GameName = "Jeu 1",
                            Score = 230
                        },
                        new
                        {
                            Id = 8,
                            FamilyId = "featherington",
                            GameName = "Jeu 1",
                            Score = 230
                        },
                        new
                        {
                            Id = 9,
                            FamilyId = "danbury",
                            GameName = "Jeu 1",
                            Score = 230
                        },
                        new
                        {
                            Id = 10,
                            FamilyId = "sharma",
                            GameName = "Jeu 1",
                            Score = 230
                        },
                        new
                        {
                            Id = 11,
                            FamilyId = "hastings",
                            GameName = "Jeu 2",
                            Score = 230
                        },
                        new
                        {
                            Id = 12,
                            FamilyId = "bridgerton",
                            GameName = "Jeu 2",
                            Score = 230
                        },
                        new
                        {
                            Id = 13,
                            FamilyId = "featherington",
                            GameName = "Jeu 2",
                            Score = 230
                        },
                        new
                        {
                            Id = 14,
                            FamilyId = "danbury",
                            GameName = "Jeu 2",
                            Score = 230
                        },
                        new
                        {
                            Id = 15,
                            FamilyId = "sharma",
                            GameName = "Jeu 2",
                            Score = 230
                        },
                        new
                        {
                            Id = 16,
                            FamilyId = "hastings",
                            GameName = "Jeu 3",
                            Score = 230
                        },
                        new
                        {
                            Id = 17,
                            FamilyId = "bridgerton",
                            GameName = "Jeu 3",
                            Score = 230
                        },
                        new
                        {
                            Id = 18,
                            FamilyId = "featherington",
                            GameName = "Jeu 3",
                            Score = 230
                        },
                        new
                        {
                            Id = 19,
                            FamilyId = "danbury",
                            GameName = "Jeu 3",
                            Score = 230
                        },
                        new
                        {
                            Id = 20,
                            FamilyId = "sharma",
                            GameName = "Jeu 3",
                            Score = 230
                        },
                        new
                        {
                            Id = 21,
                            FamilyId = "hastings",
                            GameName = "Whistledown",
                            Score = 0
                        },
                        new
                        {
                            Id = 22,
                            FamilyId = "bridgerton",
                            GameName = "Whistledown",
                            Score = -10
                        },
                        new
                        {
                            Id = 23,
                            FamilyId = "featherington",
                            GameName = "Whistledown",
                            Score = 0
                        },
                        new
                        {
                            Id = 24,
                            FamilyId = "danbury",
                            GameName = "Whistledown",
                            Score = -10
                        },
                        new
                        {
                            Id = 25,
                            FamilyId = "sharma",
                            GameName = "Whistledown",
                            Score = 0
                        });
                });

            modelBuilder.Entity("BridgertonGame.Server.Data.Entities.PublicationCooldown", b =>
                {
                    b.Property<string>("FamilyId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("LastPublicationTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("FamilyId");

                    b.ToTable("PublicationCooldowns");
                });

            modelBuilder.Entity("BridgertonGame.Server.Data.Entities.QuizAnswerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AnsweredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("QuestionNumber")
                        .HasColumnType("int");

                    b.Property<string>("SelectedAnswer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "QuestionNumber")
                        .IsUnique();

                    b.ToTable("QuizAnswers");
                });

            modelBuilder.Entity("BridgertonGame.Server.Data.Entities.QuizEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OptionA")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OptionB")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OptionC")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OptionD")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("QuestionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionNumber")
                        .IsUnique();

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("BridgertonGame.Server.Data.Entities.QuizStateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentQuestionNumber")
                        .HasColumnType("int");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("QuizStates");
                });

            modelBuilder.Entity("BridgertonGame.Server.Data.Entities.Vote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FamilyId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("VotedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("VotedForId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("VoterId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("BridgertonGame.Server.Data.Entities.VoteResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CorrectVotes")
                        .HasColumnType("int");

                    b.Property<string>("FamilyId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IncorrectVotes")
                        .HasColumnType("int");

                    b.Property<int>("PointsAwarded")
                        .HasColumnType("int");

                    b.Property<DateTime>("RevealedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("VoteResults");
                });

            modelBuilder.Entity("BridgertonGame.Server.Data.Entities.WhistledownPenalty", b =>
                {
                    b.Property<string>("FamilyId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Penalty")
                        .HasColumnType("int");

                    b.HasKey("FamilyId");

                    b.ToTable("WhistledownPenalties");

                    b.HasData(
                        new
                        {
                            FamilyId = "hastings",
                            Penalty = 0
                        },
                        new
                        {
                            FamilyId = "bridgerton",
                            Penalty = -10
                        },
                        new
                        {
                            FamilyId = "featherington",
                            Penalty = 0
                        },
                        new
                        {
                            FamilyId = "danbury",
                            Penalty = -10
                        },
                        new
                        {
                            FamilyId = "sharma",
                            Penalty = 0
                        });
                });

            modelBuilder.Entity("BridgertonGame.Shared.Models.Article", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FamilyId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Content = "La notation que la personne va écrire",
                            FamilyId = "hastings",
                            FamilyName = "Hastings",
                            PublishedAt = new DateTime(2026, 3, 18, 5, 39, 25, 940, DateTimeKind.Utc).AddTicks(815),
                            Title = "Chers amis lecteurs,"
                        },
                        new
                        {
                            Id = "2",
                            Content = "Un événement des plus intéressants s'est déroulé lors du dernier bal...",
                            FamilyId = "bridgerton",
                            FamilyName = "Bridgerton",
                            PublishedAt = new DateTime(2026, 3, 18, 7, 39, 25, 940, DateTimeKind.Utc).AddTicks(815),
                            Title = "Chers amis lecteurs,"
                        },
                        new
                        {
                            Id = "3",
                            Content = "Les rumeurs circulent à propos d'une certaine famille...",
                            FamilyId = "featherington",
                            FamilyName = "Featherington",
                            PublishedAt = new DateTime(2026, 3, 18, 9, 39, 25, 940, DateTimeKind.Utc).AddTicks(815),
                            Title = "Chers amis lecteurs,"
                        },
                        new
                        {
                            Id = "4",
                            Content = "Les secrets de la haute société ne me sont pas étrangers...",
                            FamilyId = "hastings",
                            FamilyName = "Hastings",
                            PublishedAt = new DateTime(2026, 3, 18, 11, 39, 25, 940, DateTimeKind.Utc).AddTicks(815),
                            Title = "Chers amis lecteurs,"
                        },
                        new
                        {
                            Id = "5",
                            Content = "Une nouvelle intrigue secoue les salons londoniens...",
                            FamilyId = "danbury",
                            FamilyName = "Danbury",
                            PublishedAt = new DateTime(2026, 3, 18, 13, 39, 25, 940, DateTimeKind.Utc).AddTicks(815),
                            Title = "Chers amis lecteurs,"
                        });
                });

            modelBuilder.Entity("BridgertonGame.Shared.Models.Family", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LadyWhistledownId")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<bool>("Revealed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("VotingEnabled")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Families");

                    b.HasData(
                        new
                        {
                            Id = "hastings",
                            LadyWhistledownId = "h1",
                            Name = "Hastings",
                            Points = 230,
                            Rank = 1,
                            Revealed = false,
                            VotingEnabled = false
                        },
                        new
                        {
                            Id = "bridgerton",
                            LadyWhistledownId = "b1",
                            Name = "Bridgerton",
                            Points = 210,
                            Rank = 2,
                            Revealed = false,
                            VotingEnabled = false
                        },
                        new
                        {
                            Id = "featherington",
                            LadyWhistledownId = "f1",
                            Name = "Featherington",
                            Points = 180,
                            Rank = 3,
                            Revealed = false,
                            VotingEnabled = false
                        },
                        new
                        {
                            Id = "danbury",
                            Name = "Danbury",
                            Points = 150,
                            Rank = 4,
                            Revealed = false,
                            VotingEnabled = false
                        },
                        new
                        {
                            Id = "sharma",
                            LadyWhistledownId = "s1",
                            Name = "Sharma",
                            Points = 120,
                            Rank = 5,
                            Revealed = false,
                            VotingEnabled = false
                        });
                });

            modelBuilder.Entity("BridgertonGame.Shared.Models.Player", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FamilyId")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsLadyWhistledown")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = "h1",
                            Code = "CELIA2024",
                            FamilyId = "hastings",
                            ImageUrl = "images/AdminAvatar.png",
                            IsLadyWhistledown = true,
                            Name = "Célia Hastings",
                            Role = "Lady Whistledown",
                            Title = "DUCHESSE"
                        },
                        new
                        {
                            Id = "h2",
                            Code = "FANNY2024",
                            FamilyId = "hastings",
                            ImageUrl = "images/AdminAvatar.png",
                            IsLadyWhistledown = false,
                            Name = "Fanny Hastings",
                            Role = "Invitée",
                            Title = "DUCHESSE"
                        },
                        new
                        {
                            Id = "h3",
                            Code = "HUGO2024",
                            FamilyId = "hastings",
                            ImageUrl = "images/AdminAvatar.png",
                            IsLadyWhistledown = false,
                            Name = "Hugo Hastings",
                            Role = "Invité",
                            Title = "DUC"
                        },
                        new
                        {
                            Id = "b1",
                            Code = "DAPHNE2024",
                            FamilyId = "bridgerton",
                            ImageUrl = "images/AdminAvatar.png",
                            IsLadyWhistledown = true,
                            Name = "Daphné Bridgerton",
                            Role = "Lady Whistledown",
                            Title = "DUCHESSE"
                        },
                        new
                        {
                            Id = "b2",
                            Code = "SIMON2024",
                            FamilyId = "bridgerton",
                            ImageUrl = "images/AdminAvatar.png",
                            IsLadyWhistledown = false,
                            Name = "Simon Bridgerton",
                            Role = "Invité",
                            Title = "DUC"
                        },
                        new
                        {
                            Id = "b3",
                            Code = "ELOISE2024",
                            FamilyId = "bridgerton",
                            ImageUrl = "images/AdminAvatar.png",
                            IsLadyWhistledown = false,
                            Name = "Eloïse Bridgerton",
                            Role = "Invitée",
                            Title = "LADY"
                        },
                        new
                        {
                            Id = "f1",
                            Code = "PENELOPE2024",
                            FamilyId = "featherington",
                            ImageUrl = "images/AdminAvatar.png",
                            IsLadyWhistledown = true,
                            Name = "Penelope Featherington",
                            Role = "Lady Whistledown",
                            Title = "LADY"
                        },
                        new
                        {
                            Id = "f2",
                            Code = "PORTIA2024",
                            FamilyId = "featherington",
                            ImageUrl = "images/AdminAvatar.png",
                            IsLadyWhistledown = false,
                            Name = "Portia Featherington",
                            Role = "Invitée",
                            Title = "LADY"
                        },
                        new
                        {
                            Id = "d1",
                            Code = "AGATHA2024",
                            FamilyId = "danbury",
                            ImageUrl = "images/AdminAvatar.png",
                            IsLadyWhistledown = false,
                            Name = "Agatha Danbury",
                            Role = "Maîtresse de soirée",
                            Title = "LADY"
                        },
                        new
                        {
                            Id = "d2",
                            Code = "WILL2024",
                            FamilyId = "danbury",
                            ImageUrl = "images/AdminAvatar.png",
                            IsLadyWhistledown = false,
                            Name = "Will Danbury",
                            Role = "Invité",
                            Title = "LORD"
                        },
                        new
                        {
                            Id = "s1",
                            Code = "KATE2024",
                            FamilyId = "sharma",
                            ImageUrl = "images/AdminAvatar.png",
                            IsLadyWhistledown = true,
                            Name = "Kate Sharma",
                            Role = "Lady Whistledown",
                            Title = "LADY"
                        },
                        new
                        {
                            Id = "s2",
                            Code = "EDWINA2024",
                            FamilyId = "sharma",
                            ImageUrl = "images/AdminAvatar.png",
                            IsLadyWhistledown = false,
                            Name = "Edwina Sharma",
                            Role = "Invitée",
                            Title = "LADY"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
